# Generated by Django 3.2.4 on 2021-06-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raydocs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
    ]
